language: node_js
node_js: node
cache:
  npm: true
  bundler: true
jobs:
  include:
  - stage: install
    script: npm i
  - stage: build
    script: npx parcel build ./client/public/index.html
  - stage: deploy
    script: skip
    deploy:
      provider: heroku
      api_key:
        secure: eCd7pkQtQwr/7E3zzgkjrVzWLeDCMRyIsxHbys6pDe+L67wQBkHI/nbTbMfhUwBiSWTiJgpEEmzB+S0qxJeNyehQJypS6eIYpWwoVpjJ7dFVxathReVs8SQkZC+on6zETPahI3ooS2Rs/ttP6HWeFf5zlXjNqJ4tOgSrSICR3d2ZAE4GRo2+YpRhtEw/pJRMXO3c0iySK5t+/2t35VJA4e3UltjhKfcpF0sKMihch5oAx8MGORGZzZPv6OSpd9Z7/l/0Wz2mVngMAb1CJRX4vaJNtA4KTpixyc8t6LOqsEGUt81gzgCXnVgzKN86lSvoGHl5jppp0c8KX0/Ij0gLAqFcng5GNsiXDlUjTPjoUu+X6S2h0tT6UU87FUxpfmLLo5QBUPTor8SmLbDjz3cEOi1Gt5zIUrO9hHEVqIefLhzBt8BymwsW138vXK47F5zzTntZrHozcpNE0dnqUmuLksWSjB3D9wACH58bnXinJM391Q6wFfeU8INGEmKfz4a29Myh4p1kchNtwmX+lBVRUO5UmR7qq1O8pM3Aso+pBxTJB8BgRqZSDjeRdLFnZr1MdeqESQiWeLvdUZ4RUypy1uvZ0Ax4Zsxl8XU2sUG/lobc/7LxXHp9RdXT/hlV2nHv0rj0c/ZJdtJr9BGlzvtMpYw4v9GmjuWOVgN/nz+WST8=
      app: ancient-woodland-75923
      on:
        branch: master