language: node_js
node_js: node
cache:
  npm: true
  bundler: true
  directories:
    - node_modules
jobs:
  include:
    - stage: install
      script: npm i
    - stage: build
      script: npx parcel build ./public/index.html
    - stage: deploy
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: 78656e67-d3cf-4b4b-bcc2-dab682982bde
        app: ancient-woodland-75923
        skip_cleanup: true
