cache: npm
jobs:
  include:
    - stage: install
      script: npm i
    - stage: build
      script: npm run build
    - stage: deploy
      script: skip
      deploy:
        provider: heroku
        secure:
          api_key: '78656e67-d3cf-4b4b-bcc2-dab682982bde'
        run: 'node server.js'
